#True to allow the DIY Workbench to craft items, false to disable
enable_diy_workbench = true
#The percent chance of an instant jackpot, in addition to the natural 6.25% chance
#Range: 0.0 ~ 100.0
slot_machine_jackbox_chance = 15.0

